branches:
  only:
    - master
    

language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed mostafaibrahim/udagram-api-feed:latest
  - docker build -t udagram-api-user ./udagram-api-users
  - docker tag udagram-api-user mostafaibrahim/udagram-api-user:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend mostafaibrahim/udagram-frontend:latest
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy mostafaibrahim/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mostafaibrahim/udagram-api-feed:latest
  - docker push mostafaibrahim/udagram-api-user:latest
  - docker push mostafaibrahim/udagram-frontend:latest
  - docker push mostafaibrahim/reverseproxy:latest
